#!/usr/bin/env bash
# Open $EDITOR to edit a YAML and then apply it with kubernetes
set -euo pipefail

VERSION="0.1.4"

recovery_file=/tmp/kubectl-inline/last.yaml
resource=""
recover=""
namespace=""
tmp_file_creation=""
apply=""
template_directory=""

if kubectl krew list | grep -q inline > /dev/null 2>&1
then
  template_directory="${KREW_ROOT:-$HOME/.krew}/store/inline/v$VERSION/templates"
else # It's not called as a plugin, therefore it must be close to the templates
  # Magic incantation from https://stackoverflow.com/a/246128/15768984
  template_directory="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )/templates"
fi

help() {
  echo "kubectl inline [flags] [resource type]"
  echo "  -r|--recover"
  echo "  -n|--namespace"
  echo "  -h|--help"

  exit 2
}

version() {
  echo "kubectl-inline v$VERSION"

  exit 2
}

# Set up command-line options
SHORT="n:,r,a,h,v;"
LONG="namespace:,recover,apply,help,version"
OPTS=$(getopt --name "kubectl-inline" --options "$SHORT" --longoptions "$LONG" -- "$@")

if [[ "$#" == 0 ]]
then
  help
fi

eval set -- "$OPTS"


# Prepare a file to keep the last inline file made
mkdir -p "$(dirname "$recovery_file")"
touch "$recovery_file"

# Parse arguments
while [[ $# -gt 0 ]]; do
  case $1 in
    -n|--namespace)
      namespace="$2"
      shift 2
      ;;
    -r|--recover)
      recover="TRUE"
      shift
      ;;
    -a|--apply)
      apply="TRUE"
      shift
      ;;
    -h|--help)
      help
      ;;
    -v|--version)
      version
      ;;
    --)
      shift;
      break
      ;;
  esac
done

if [[ -n "$recover" && -n "${1:-}" ]]
then
  >&2 echo "Can't use -r|--recover with a resource type"
fi
                                                        
if [[ -n "${1:-}" ]]
then
  case $1 in                                              
    cm|configmap)                                          
      resource="configmap"                                 
      ;;                                             
    secret)                                                
      resource="secret"
      ;;
    po|pod)
      resource="pod"
      ;;
    deploy|deployment)
      resource="deployment"
      ;;
    svc|service)
      resource="service"
      ;;
    ing|ingress)
      resource="ingress"
      ;;
    pg|postgresql)
      resource="postgresql"
      ;;
    ns|namespace)
      if [ -n "$namespace" ]
      then
        >&2 echo "Cannot provide the -n|--namespace flag for a namespace resource"
        exit 1
      fi
      resource="namespace"
      ;;
  esac
fi

# XXX: The weird variable substitution prevents errors about it being unset
if [ -n "${2-""}" ]
then
  >&2 echo "Only one resource type allowed"
  exit 1
fi

# Create a temporary file to edit
file=$(mktemp --suffix ".yaml")
trap 'rm $file' EXIT

if [ -n "$recover" ] # If recovering last file
then 
  cat "$recovery_file" > "$file" # Put its content into $file
elif [ -n "$resource" ] # Else, if creating a new resource with a template
then
  cat "$template_directory/$resource.yaml" > "$file"
  if [ -n "$namespace" ]
  then
    sed -i "s/%namespace%/$namespace/" "$file"
  else
    sed -i "/.*%namespace%.*/d" "$file"
  fi
fi

# Open it in $EDITOR
tmp_file_creation=$(stat -c "%Z" "$file")
"$EDITOR" "$file"
tmp_file_modification=$(stat -c "%Z" "$file")

# Save contents in /tmp/kubectl-inline/last to be able to recover it with -r
cp "$file" "$recovery_file"

if [[ "$tmp_file_creation" != "$tmp_file_modification" ]]
then # File was modified
  cat "$file"
  if [ -n "$apply" ]
  then
    kubectl ${namespace:+-n $namespace} apply -f "$file"
  fi
else # File wasn't modified
  >&2 echo "No changes applied"
fi

