apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: inline
spec:
  version: "v0.1.3"
  homepage: https://github.com/huuff/kubectl-inline
  shortDescription: "Easily create a resource from the command-line."
  description: |
    Allows creating a resorce quickly from the command line in your `$EDITOR`. Optionally, you can choose a template to base your resource on.
  platforms:
  - selector:
      matchExpressions:
      - key: "os"
        operator: "In"
        values:
        - linux
    uri: https://github.com/huuff/kubectl-inline/archive/refs/tags/0.1.3.zip
    sha256: d54eff88787af3a723b855e5e2f96149d626d18d27864a118ff60c1a785b1a10
    files:
      - from: "kubectl-inline*/kubectl-inline"
        to: .
      - from: "kubectl-inline*/LICENSE"
        to: .
      - from: "kubectl-inline*/templates"
        to: .
    bin: "kubectl-inline"

