apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: kubectl-inline
spec:
  version: "v0.1.2"
  homepage: https://github.com/huuff/kubectl-inline
  shortDescription: "Easily create a resource from the command-line."
  description: |
    Allows creating a resorce quickly from the command line in your `$EDITOR`. Optionally, you can choose a template to base your resource on.
  platforms:
  - selector:
      matchExpressions:
      - key: "os"
        operator: "In"
        values:
        - linux
    uri: https://github.com/huuff/kubectl-inline/archive/refs/tags/0.1.2.zip
    sha256: 1057475555a283398d084585500b0eed5abdeab898d5b984f9678757c23c6e7b
    bin: "kubectl-inline"

