apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: 
subjects:
- kind: 
  name: 
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: 
  apiGroup: rbac.authorization.k8s.io
