kind: "postgresql"
apiVersion: "acid.zalan.do/v1"
metadata:
  name: 
  namespace: %namespace%
  labels:
    team: acid
spec:
  teamId: "acid"
  postgresql:
    version: "14"
  numberOfInstances: 1
  volume:
    size: "10Gi"
  users:
    %user%: []
  databases:
    %database%: %user%
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 500m
      memory: 500Mi
